[workspace]
members = [
    "crates/oxidize_core",
    "crates/verified_engine",
    "crates/verified_engine_macros",
    "crates/math_core",
    "crates/ai",
    "crates/applied",
    "crates/biology",
    "crates/climate",
    "crates/epidemiology",
    "crates/physics",
    "crates/pure_math",
    "math_explorer_gui",
    "crates/rug_mock",
    "crates/wigner_mock"
]
resolver = "2"

[workspace.lints.clippy]
too_many_lines = "deny"
cognitive_complexity = "deny"

