[links]
generative_turbulence = "generative_turbulence.tex"
ai = "ai.tex"
optics = "optics.tex"
standard_model = "standard_model.tex"
stat_mech = "stat_mech.tex"
fluid_dynamics = "fluid_dynamics.tex"
chaos = "chaos.tex"
nuclear = "nuclear.tex"
quantum = "quantum.tex"
medical = "medical.tex"
astrophysics = "astrophysics.tex"
mri = "mri.tex"
high_energy = "high_energy.tex"
solid_state = "solid_state.tex"
pure_math = "pure_math.tex"
epidemiology = "epidemiology.tex"
grpo = "grpo.tex"
engineering = "engineering.tex"
win_ratio = "win_ratio.tex"
cannibalism = "cannibalism.tex"
game_theory = "game_theory.tex"
algorithms = "algorithms.tex"
freesurfer = "freesurfer.tex"
favoritism = "favoritism.tex"
clinical_trials = "clinical_trials.tex"
lorahub = "lorahub.tex"
battery_degradation = "battery_degradation.tex"
pharmacokinetics = "pharmacokinetics.tex"
isosurface = "isosurface.tex"
climate = "climate.tex"
biology = "biology.tex"
modular_polynomials_review_mod = "modular_polynomials_review.tex"
dijkstra_mod = "dijkstra.tex"
cera_framework_mod = "cera_framework.tex"
domain_physics = "self_calibration_paper.tex"
tensors_mod = "tensors.tex"
ualbf_quasiperfect_mod = "ualbf_quasiperfect.tex"
hurwitz_kronecker_mod = "hurwitz_kronecker.tex"
quasiperfect_alcf_mod = "quasiperfect_alcf.tex"
math_commons = "essay.tex"
gaussian_splatting_mod = "gaussian_splatting.tex"
chaos_theory_mod = "chaos_theory.tex"
attention_is_all_you_need_rust_mod = "attention_is_all_you_need_rust.tex"
partitions_implementation_mod = "partitions_implementation.tex"
