[package]
name = "oxidize_core"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { workspace = true }
async-recursion = { workspace = true }
quote = { workspace = true }
rand = { workspace = true, features = ["std", "alloc"] }
rand_chacha = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["derive"] }
syn = { workspace = true, features = ["full", "visit"] }
thiserror = { workspace = true }
toml = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true, features = ["Window", "Document", "HtmlElement", "Blob", "Url", "BlobPropertyBag", "Response"] }
wasm-bindgen-futures = { workspace = true }

[dev-dependencies]
approx = { workspace = true }

[lints]
workspace = true
