//! Physical Principles of Non-Contact Optical Sensing
//!
//! This module models the physical interactions of light propagation, reflection, and detection.

use std::f64::consts::PI;

/// Calculates the Lambertian order (n) based on the light source's half-power angle.
///
/// # Arguments
///
/// * `phi_half` - The half-power angle in radians.
///
/// # Returns
///
/// * `f64` - The Lambertian order n.
///
/// # Formula
///
/// $n = \frac{-\ln(2)}{\ln(\cos(\phi_{1/2}))}$
#[verified_engine::verified]
pub fn calculate_lambertian_order(phi_half: f64) -> f64 {
    -2.0f64.ln() / phi_half.cos().ln()
}

/// Calculates the received optical power (P_d) at the detector using the Lambertian model.
///
/// # Arguments
///
/// * `n` - The Lambertian order.
/// * `a` - The intercepted area of the photodetector.
/// * `p_t` - Transmitted optical power from the source.
/// * `d` - The distance between the source and the detector.
/// * `phi` - The irradiance angle (angle of emission from the source) in radians.
/// * `theta` - The incident angle (angle of arrival at the detector) in radians.
/// * `gamma` - The empirical path-loss exponent.
///
/// # Returns
///
/// * `f64` - Received optical power P_d.
///
/// # Formula
///
/// $P_d = \frac{(n + 1) A P_t}{2 \pi d^\gamma} \cos^n(\phi) \cos(\theta)$
#[verified_engine::verified]
pub fn calculate_received_power(
    n: f64,
    a: f64,
    p_t: f64,
    d: f64,
    phi: f64,
    theta: f64,
    gamma: f64,
) -> f64 {
    let numerator = (n + 1.0) * a * p_t;
    let denominator = 2.0 * PI * d.powf(gamma);
    let angular_term = phi.cos().powf(n) * theta.cos();

    (numerator / denominator) * angular_term
}

/// Calculates the total photocurrent generated by the photodiode.
///
/// # Arguments
///
/// * `p_r` - The scattered optical power received by the photodetector.
/// * `i_d` - The photodetector's dark current.
/// * `r_pd` - The responsivity of the photodetector (Amps/Watt).
///
/// # Returns
///
/// * `f64` - Total photocurrent i_pd.
///
/// # Formula
///
/// $i_{pd} = i_d + R_{pd} P_r$
#[verified_engine::verified]
pub fn calculate_photocurrent(p_r: f64, i_d: f64, r_pd: f64) -> f64 {
    i_d + r_pd * p_r
}

/// Calculates the final output voltage from the transimpedance amplifier (TIA).
///
/// # Arguments
///
/// * `i_pd` - The total photocurrent.
/// * `g_pd` - The transimpedance gain of the amplifier (Volts/Amp).
///
/// # Returns
///
/// * `f64` - Output voltage V_sig.
///
/// # Formula
///
/// $V_{sig} = g_{pd} i_{pd}$
#[verified_engine::verified]
pub fn calculate_tia_output(i_pd: f64, g_pd: f64) -> f64 {
    g_pd * i_pd
}
