[package]
name = "markdown_tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
math_commons = { path = "../math_commons" }
math_explorer = { path = "../../math_explorer", features = ["pure_math", "applied", "ai", "biology", "climate", "epidemiology", "physics"] }

thiserror = "1.0"
eframe = "0.33"

[lints]
workspace = true
