[package]
name = "domain_climate"
version = "0.4.0"
edition = "2024"

[dependencies]
rustfft = "6.2.0"
nalgebra = "0.34.0"
quadrature = "0.1.2"
rand = "0.8.6"
statrs = "0.17.0"
petgraph = "0.6.4"
rand_distr = "0.4.3"
num-complex = "0.4.6"
thiserror = "2.0.18"
num-traits = "0.2.19"
serde_json = "1.0.150"
serde = { version = "1.0.228", features = ["derive"] }
oxidize_core = { path = "../oxidize_core" }
verified_engine = { version = "0.1.0", path = "../verified_engine" }

math_commons = { path = "../math_commons" }
diagnostics = { path = "../diagnostics", features = ["federated"] }
pure_math = { path = "../pure_math" }
domain_ai = { path = "../domain_ai" }



[target.'cfg(not(target_arch = "wasm32"))'.dependencies]

[target.'cfg(target_arch = "wasm32")'.dependencies]

[dev-dependencies]
approx = "0.5.1"

[profile.release]
overflow-checks = true
[lints]
workspace = true
