[package]
name = "math_commons"
version = "0.4.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
verified_engine = { version = "0.1.0", path = "../verified_engine" }
diagnostics = { path = "../diagnostics" }





[target.'cfg(not(target_arch = "wasm32"))'.dependencies]

[target.'cfg(target_arch = "wasm32")'.dependencies]

[dev-dependencies]
approx = { workspace = true }

[lints]
workspace = true
