[package]
name = "verified_engine_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = { workspace = true, features = ["span-locations"] }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "fold", "visit-mut", "visit"] }

[lib]
proc-macro = true
[dev-dependencies]
approx = { workspace = true }

[lints]
workspace = true
