[package]
name = "math_explorer_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.33.3"
egui_plot = "0.34.1"

nalgebra = "0.34.0"
math_explorer = { path = "../math_explorer", features = ["ai", "applied", "biology", "climate", "epidemiology", "physics", "pure_math"] }
num-complex = "0.4.6"
rand = "0.8.5"
petgraph = "0.6.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.100"
