[package]
name = "math_explorer_gui"
version = "0.1.0"
edition = "2021"

[features]
default = ["domain_logic", "ai", "applied", "biology", "climate", "epidemiology", "physics", "pure_math"]
domain_logic = ["dep:math_explorer"]
pure_math = ["math_explorer/pure_math"]
applied = ["math_explorer/applied", "pure_math"]
ai = ["math_explorer/ai", "pure_math"]
biology = ["math_explorer/biology", "applied", "pure_math"]
climate = ["math_explorer/climate", "ai"]
epidemiology = ["math_explorer/epidemiology", "pure_math"]
physics = ["math_explorer/physics", "applied", "pure_math"]

[dependencies]
eframe = "0.33.3"
egui_plot = "0.34.1"

nalgebra = "0.34.0"
oxidize_core = { path = "../crates/oxidize_core" }
math_explorer = { path = "../math_explorer", optional = true }
math_commons = { path = "../crates/math_commons" }
num-complex = "0.4.6"
rand = "0.8.5"
petgraph = "0.6.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.2.17", features = ["js"] }
wasm-bindgen = "0.2.100"
js-sys = "0.3.60"
web-sys = { version = "0.3.60", features = ["Window", "Document", "HtmlCanvasElement", "Element", "Node"] }

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen-futures = "0.4.72"
