[build]
target = "wasm32-unknown-unknown"
rustflags = ["-C", "target-feature=+atomics,+bulk-memory"]

[serve]
headers = { "Cross-Origin-Opener-Policy" = "same-origin", "Cross-Origin-Embedder-Policy" = "require-corp" }
