[package]
name = "math_explorer"
version = "0.4.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
math_explorer_core = { path = "../crates/math_explorer_core" }
rustfft = "6.2.0"
nalgebra = "0.34.0"
quadrature = "0.1.2"
rand = "0.8.6"
wigner-symbols = "0.5.0"
rug = "1.28.0"
statrs = "0.17.0"
petgraph = "0.6.4"
rand_distr = "0.4.3"
num-complex = "0.4.6"
thiserror = "2.0.18"
num-traits = "0.2.19"

[[test]]
name = "elliptic_curves"
path = "tests/elliptic_curves.rs"

[[test]]
name = "algorithmic_information"
path = "tests/algorithmic_information.rs"

[dev-dependencies]
approx = "0.5.1"
rand = "0.8.6"

[dev-dependencies.criterion]
version = "0.5.1"

[[bench]]
name = "sorting_benchmark"
harness = false

[features]
default = []
ai = []
applied = []
biology = []
climate = []
epidemiology = []
physics = []
pure_math = []

