use math_explorer::applied::isosurface::{Point3D, VoxelGrid, extract_isosurface};
use std::fs::File;
use std::io::Write;

/// This example generates a mesh for a Torus using the Marching Cubes algorithm
/// and exports it to a Wavefront OBJ file.
fn main() -> std::io::Result<()> {
    println!("Generating Torus SDF...");

    let width = 64;
    let height = 64;
    let depth = 64;
    let total_size = width * height * depth;

    // Torus parameters
    let major_radius = 2.0;
    let minor_radius = 0.8;

    // Grid Setup (Spatial extent from -4 to 4)
    let min_bound = -4.0;
    let max_bound = 4.0;
    let range = max_bound - min_bound;
    let step = range / (width as f32);

    let mut data = Vec::with_capacity(total_size);

    for z in 0..depth {
        let z_coord = min_bound + (z as f32) * step;
        for y in 0..height {
            let y_coord = min_bound + (y as f32) * step;
            for x in 0..width {
                let x_coord = min_bound + (x as f32) * step;

                // Torus SDF: f(x,y,z) = sqrt((sqrt(x^2 + y^2) - R)^2 + z^2) - r
                let len_xy = (x_coord * x_coord + y_coord * y_coord).sqrt();
                let dist =
                    ((len_xy - major_radius).powi(2) + z_coord * z_coord).sqrt() - minor_radius;

                // Marching Cubes expects values where < threshold is "inside".
                // SDF is typically negative inside, positive outside.
                // We'll use threshold = 0.0.
                data.push(dist);
            }
        }
    }

    let grid = VoxelGrid {
        width,
        height,
        depth,
        data,
        voxel_size: Point3D::new(step, step, step),
        origin: Point3D::new(min_bound, min_bound, min_bound),
    };

    println!("Extracting Isosurface...");
    let mesh = extract_isosurface(&grid, 0.0).expect("Failed to extract isosurface");
    println!("Generated {} triangles.", mesh.triangles.len());

    // Export to OBJ
    let filename = "torus.obj";
    let mut file = File::create(filename)?;

    writeln!(file, "# Generated by Math Explorer")?;

    // Write vertices
    // Note: OBJ indices are 1-based and global.
    // Marching cubes produces independent triangles, duplicating vertices.
    // For a simple example, we won't deduplicate vertices.
    for tri in &mesh.triangles {
        writeln!(file, "v {} {} {}", tri.v1.x, tri.v1.y, tri.v1.z)?;
        writeln!(file, "v {} {} {}", tri.v2.x, tri.v2.y, tri.v2.z)?;
        writeln!(file, "v {} {} {}", tri.v3.x, tri.v3.y, tri.v3.z)?;
    }

    // Write normals
    for tri in &mesh.triangles {
        writeln!(file, "vn {} {} {}", tri.n1.x, tri.n1.y, tri.n1.z)?;
        writeln!(file, "vn {} {} {}", tri.n2.x, tri.n2.y, tri.n2.z)?;
        writeln!(file, "vn {} {} {}", tri.n3.x, tri.n3.y, tri.n3.z)?;
    }

    // Write faces
    let mut offset = 1;
    for _ in 0..mesh.triangles.len() {
        // format: f v1//vn1 v2//vn2 v3//vn3
        writeln!(
            file,
            "f {}//{} {}//{} {}//{}",
            offset,
            offset,
            offset + 1,
            offset + 1,
            offset + 2,
            offset + 2
        )?;
        offset += 3;
    }

    println!("Mesh saved to {}", filename);
    println!("You can view this file in Blender, MeshLab, or any 3D viewer.");

    Ok(())
}
